import type { Config } from "tailwindcss";

// Ported 1:1 from the original site's js/tailwind-config.js so the visual
// design carries over exactly. Loaded into Tailwind v4 via the `@config`
// directive in src/index.css.
const config: Config = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#f5dfc4",
        "surface-container-lowest": "#ffffff",
        primary: "#030813",
        "on-background": "#1a1c1a",
        "on-secondary-container": "#226d6c",
        "on-secondary-fixed": "#002020",
        "primary-container": "#1a202c",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "surface-container": "#efeeeb",
        "secondary-container": "#a6eceb",
        "on-primary": "#ffffff",
        "primary-fixed": "#dde2f3",
        "on-secondary-fixed-variant": "#00504f",
        "on-error-container": "#93000a",
        tertiary: "#0e0700",
        surface: "#faf9f6",
        "surface-dim": "#dbdad7",
        "on-surface": "#1a1c1a",
        "inverse-surface": "#2f312f",
        "on-primary-container": "#828796",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#524531",
        "secondary-fixed": "#a9efed",
        "surface-variant": "#e3e2e0",
        "inverse-on-surface": "#f2f1ee",
        outline: "#76777c",
        "on-tertiary-container": "#96856d",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e9e8e5",
        "outline-variant": "#c6c6cc",
        "primary-fixed-dim": "#c1c6d7",
        background: "#faf9f6",
        "secondary-fixed-dim": "#8dd3d1",
        "surface-bright": "#faf9f6",
        "error-container": "#ffdad6",
        "surface-tint": "#585e6c",
        secondary: "#1c6968",
        "on-surface-variant": "#45474c",
        "inverse-primary": "#c1c6d7",
        "surface-container-highest": "#e3e2e0",
        "on-primary-fixed": "#161c27",
        "tertiary-fixed-dim": "#d8c3a9",
        "on-tertiary-fixed": "#241a09",
        "on-primary-fixed-variant": "#414754",
        "tertiary-container": "#291e0d",
        "surface-container-low": "#f4f3f1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "20px",
        "section-padding-desktop": "120px",
        "section-padding-mobile": "64px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["Manrope"],
        "label-caps": ["Inter"],
        "headline-md": ["Manrope"],
        "display-lg-mobile": ["Manrope"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
};

export default config;
